### ISSUE TITLE
Make MonzoObject serializable to JSON?

### ISSUE THREAD

**Issue by beveradb** [pawelad/pymonzo#19]
I was hoping to be able to do `json.dumps(monzoTransaction)` but get `TypeError(repr(o) + " is not JSON serializable")` - I'm working around this, but it would be really handy for the use case I'm working on (a tool to batch-import transactions into YNAB)

**Comment by pawelad** [comment]
First of all, sorry for replying so late. The library was essential not supported since ~2017. I had some free time recently though and decided to give it some love and release v1.0.0

Since the library is using [Pydantic](https://github.com/pydantic/pydantic) now, this this should be as simple as:

```python
monzoTransaction.model_dump("json")
```
