### ISSUE TITLE
I can't authenticate with OAuth 2 - 'oauthlib.oauth2.rfc6749.errors.ServerError'

### ISSUE THREAD

**Issue by delabere** [pawelad/pymonzo#2]
I am getting errors when running the MonzoAPI() command after exporting the authorisation environment variables.

Also it is not clear from where I should get the auth code to input. Is the code the whole URL from the email or just the part after 'code='?

Thank you.

>>> m.MonzoAPI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymonzo/monzo_api.py", line 95, in __init__
    self._token = self._get_oauth_token()
  File "/usr/local/lib/python3.6/site-packages/pymonzo/monzo_api.py", line 144, in _get_oauth_token
    client_secret=self._client_secret,
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 404, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.ServerError: (server_error) Unknown error occurred
>>>

**Comment by bartonp** [comment]
@delabere if you could let us know the OS that you are using. You'll also need to always pass in client_id and client_secret into the script when you do MonzoAPI().

Below is a python 2.7 snippet which should help you out:
```
# -*- coding: utf-8 -*-
import pymonzo
from ConfigParser import ConfigParser

conf = ConfigParser()
conf.read('api_info.conf')
monzo_conf = dict(conf.items('monzo'))

client = pymonzo.MonzoAPI(client_secret=monzo_conf['client_secret'], client_id=monzo_conf['client_id'])
```

The api_info.conf file looks like the below text with the values substituted with the correct values:
```
[monzo]
client_secret=<SECRET>
client_id=<ID>
```

The 'code' part is just the url param for code and not the whole URL.

**Comment by pawelad** [comment]
OK, so I went through the [OAuth 2](https://github.com/pawelad/pymonzo#oauth-2) section of the readme step by step to see if I wasn't clear about anything. I did a couple of small changes so you can go through that again and see if that helps you.

The above exception sounds very general so my guess would be that the problem is with the variables your passing. It should look something like this (that's in Python shell):

```python
>> from pymonzo import MonzoAPI
>> m = MonzoAPI(
    client_id='oauthclient_XXX',
    client_secret='WzRwqzIVbIueWzRwqzIVbIueGu6tXqp/WzRwqzIVbIuel/TEdUmhv/WzRwqzIVbIueSJ52WzRwqzIVbIuew2', 
    auth_code='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaSI6Im9hdXRoY2xpZW50XzAwMDA5T2N2MFg0bDJBVW9OTkVkaVQiLCJleHAiOjE1MDU3MDQwNTMsImlhdCI6MTUwNTcwMDQ1MywianRp2MFg0bDJBVW9OTkVkaVQiLCJleHAiOjE1MDU3MDQwNTMsImlhdCI6MTUwNTcwMDQ1MywianRp'eyJhbGciOiJI.eyJjaSI6Im9hdXRoY2xpZW50XzAwMDA5T2N',
)
```

> Also it is not clear from where I should get the auth code to input. Is the code the whole URL from the email or just the part after 'code='?

The part you need is only the value of code, so everything after that and before `&code=` - I emphasized it in the updated README.

Also, does using only the `access_token` from Monzo playground work? That's a good starting point to see if the problem is within OAuth or is it broader.

**Comment by delabere** [comment]
Thanks for the reply and the help all.
I am using macOS Sierra (10.12.6).

**pawelad:**
Passing the variables in directly worked for me and returned an object. And this works for the Monzo playground as well.

However I don't believe that a token is being saved and refreshed on my disk, or if it is it isn't being accessed when I then pass MonzoAPI() in the future.

I want to be able to write a script that can authorise without me having to get a unique access_code every time.

In addition, how do I get my balance from the object once this works?

Thanks again - I really appreciate the help,
Sorry for taking a while to get back - have been very busy.

**Comment by delabere** [comment]
I think perhaps I just need to find the access token on my machine and then pass it as a variable into MonzoAPI()?

Can you help me find out how I can do this?

**Comment by pawelad** [comment]
> Passing the variables in directly worked for me and returned an object. And this works for the Monzo playground as well.

Could you actually access your Monzo data with that object? Did `MonzoAPI.whoami()` and `MonzoAPI.accounts()` work?

Also, if it worked with passing them explicitly then it _should_ work with passing them indirectly via environment variables. The easiest way to debug would be to just print `os.environ` before initializing the object and see if Python can actually access the environment variables.

> However I don't believe that a token is being saved and refreshed on my disk, or if it is it isn't being accessed when I then pass MonzoAPI() in the future.

Could you see if `~/.pymonzo-token` file exists on your machine? It should be created / updated when initializing with OAuth (not when using the `access_token` though). If so then your token is saved and should be automatically refreshed.

> In addition, how do I get my balance from the object once this works?

After you get an authenticated `MonzoAPI` object, calling `MonzoAPI.balance()` should work (note: you may need to pass additional `account_id` parameter if you have more then 1 card linked to your account).

**Comment by delabere** [comment]
Yes I can actually access all the data including MonzoAPI.whoami() / accounts / balance etc.

Python can recognise environment variables through os.environ

But I can't find the ~/.pymonzo-token file anywhere.

**Comment by bartonp** [comment]
Open up a terminal and do this `ls ~/.pymonzo-token*` and it should print the .pymonzo-token file. My mac for some reason is appending .db onto the end which is making some of the check fail. You can edit `src/pymonzo/config.py` file to reflect that on `TOKEN_FILE_NAME`.

**Comment by pawelad** [comment]
> Yes I can actually access all the data including MonzoAPI.whoami() / accounts / balance etc.

OK, so if this works:

```python
>> from pymonzo import MonzoAPI
>> m = MonzoAPI(
    client_id='oauthclient_XXX',
    client_secret='WzRwqzIVbIueWzRwqzIVbIueGu6tXqp/WzRwqzIVbIuel/TEdUmhv/WzRwqzIVbIueSJ52WzRwqzIVbIuew2', 
    auth_code='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaSI6Im9hdXRoY2xpZW50XzAwMDA5T2N2MFg0bDJBVW9OTkVkaVQiLCJleHAiOjE1MDU3MDQwNTMsImlhdCI6MTUwNTcwMDQ1MywianRp2MFg0bDJBVW9OTkVkaVQiLCJleHAiOjE1MDU3MDQwNTMsImlhdCI6MTUwNTcwMDQ1MywianRp'eyJhbGciOiJI.eyJjaSI6Im9hdXRoY2xpZW50XzAwMDA5T2N',
)
```

does this work?

```python
>> import os
>> from pymonzo import MonzoAPI
>> m = MonzoAPI(
    client_id=os.getenv('MONZO_CLIENT_ID'),
    client_secret=os.getenv('MONZO_CLIENT_SECRET'),
    auth_code=os.getenv('MONZO_AUTH_CODE'),
)
```

If yes, then `m = MonzoAPI()` should work as well...

> But I can't find the ~/.pymonzo-token file anywhere.

Yeah, just do what @bartonp suggested:
> Open up a terminal and do this `ls ~/.pymonzo-token*`

**Comment by delabere** [comment]
Yes I can save them as environment variables and it works.

Running the following also works and returns this:

>>$Jacks-MacBook-Pro:documents jackrickards$ ls ~/.pymonzo-token*
      /Users/jackrickards/.pymonzo-token.db

So it appears that it exists on my system.

But if I quit out of the terminal and open a new one then run MonzoAPI it wants new variables again.

**Comment by delabere** [comment]
Scrap that...I have just tried again and now I can open up a new terminal and just running:

from pymonzo import MonzoAPI
j = MonzoAPI()
j.balance()

And I get everything I needed thank you I really appreciate the help both of you!

I can now continue with my project!

I'm not sure at what point it decided to start working but I'm glad it has.

**Comment by pawelad** [comment]
> But if I quit out of the terminal and open a new one then run MonzoAPI it wants new variables again.

OK, so that's because of the `.db` extension - `pymonzo` is checking if `~/.pymonzo-token` exists and it does not.

I wonder why OS X changes that name. I'll have a look today.

> But if I quit out of the terminal and open a new one then run MonzoAPI it wants new variables again.

Yeah, that's expected because when you `export` environment variables, then don't survive shell restart. That plus the the renaming of the token files means that `pymonzo` didn't find any authentication data it can use.

**Comment by delabere** [comment]
I see.

So then it has started working since renaming the token file as ~/.pymonzo-token.db in the src/pymonzo/config.py that has solved the problem.

Perhaps as a fix this is all that is needed.

**Comment by pawelad** [comment]
> So then it has started working since renaming the token file as ~/.pymonzo-token.db in the src/pymonzo/config.py that has solved the problem.

Well, that's kinda bypassing the problem though : -)

I'm happy it works for you for now though, and I'll try to look into the weird `.db` thing.
