### ISSUE TITLE
Various URLs in the readme still refer to Mondo

### ISSUE THREAD

**Issue by nomis** [pawelad/pymonzo#21]
Various URLs in the readme still refer to `getmondo.co.uk` and need to be changed to `monzo.com` or they won't work.

**Comment by vext01** [comment]
Gah, is this why I can't authenticate? Trying now.

**Comment by pawelad** [comment]
First of all, sorry for replying so late. The library was essential not supported since ~2017. I had some free time recently though and decided to give it some love and release v1.0.0

This should be fixed now : )
