### ISSUE TITLE
Unable to access the Monzo API when running as root on raspberry pi 3

### ISSUE THREAD

**Issue by yanling-yl** [pawelad/pymonzo#25]
Hello everyone, 

I have managed to set up the API access following all the instructions in the readme, saving the client ID, client secret and auth code in the auth.py file. The codes work when I run them normally, i.e. python3 filename.py, and I can obtain my transaction data, balance, etc. with no problem. 

However, I am also using the Adafruit Neopixel library to control some LED lights at the same time. The library can be found here: https://github.com/adafruit/Adafruit_NeoPixel

Using this library apparently has two constraints: it has to be run in Python 3, and it has to be run as root. The documentation explains that "**For NeoPixels to work on Raspberry Pi, you must run the code as root! Root access is required to access the RPi peripherals.**" Further documentation can be found here: https://cdn-learn.adafruit.com/downloads/pdf/neopixels-on-raspberry-pi.pdf

**The problem is, I can't seem to run the PyMonzo codes when I run as root (i.e. sudo python3 filename.py).** The error I get is:
_Traceback (most recent call last):
    File "filename.py", line 34, in <module>
        monzo = MonzoAPI( )
    File "/usr/local/lib/python3.5/dist-packages/pymonzo/monzo_api.py", line 106, in ___init___
        "To authenticate and use Monzo public API you need to pass "
ValueError: To authenticate and use Monzo public API you need to pass (or set as environment variables either the access token or all of client ID, client secret and authentication code. For more info see https://github.com/pawelad/pymonzo#authentication_

If I run the code normally without using sudo, the error I get is:
_Can't open /dev/mem: Operation not permitted
Traceback (most recent call last):
    File "filename.py", line 66, in <module>
        neopix.show( )
    .....
    RuntimeError: ws2811_init failed with code -5 (mmap( ) failed) 
swig/python detected a memory leak of type 'ws2811_t *', no destructor found_

Does anyone know if there is a way to deconflict between these two operations, perhaps a way that pyMonzo can be run as root? 

I have tried running sudo chmod 666 /dev/mem, and running it without sudo. 

Thank you very much.

**Comment by ghost** [comment]
Hey there @Semiylyly 
To clarify, you have followed the OAuth2 authentication process for Pymonzo highlighted under https://github.com/pawelad/pymonzo#oauth-2 and have exported your credentials as environment variables so that:
> "The token is then saved on the disk (~/.pymonzo) and is automatically refreshed when needed, so all this (should) be one time only."

**Comment by pawelad** [comment]
First of all, sorry for replying so late. The library was essential not supported since ~2017. I had some free time recently though and decided to give it some love and release v1.0.0

The original issue sounds like it was about different `pymonzo` settings file path, because it defaults to user home path. To work around that, you should be able to explicitly specify the settings file path:

```python
from pymonzo import MonzoAPI
MonzoAPI.settings_path = "<path that both users can access>"
api_client = MonzoAPI()
```

I’m gonna close the issue, but let me know if you still have this problem.
