### ISSUE TITLE
Transactions List (with expand_merchants=True) fails pydantic checks

### ISSUE THREAD

**Issue by csogilvie** [pawelad/pymonzo#34]
Running `monzo_api.transactions.list(account_id=account_id, expand_merchant=True)` produces pydantic errors:

```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for MonzoTransaction
merchant.MonzoTransactionMerchant.suggested_tags
  Field required [type=missing, input_value={'id': 'merch_0000ADdaX06...: False, 'metadata': {}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
merchant.str
  Input should be a valid string [type=string_type, input_value={'id': 'merch_0000ADdaX06...: False, 'metadata': {}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
```

These look like they could be tied together...  I don't see a 'suggested_tags' option in any of the transactions I have.

**Comment by pawelad** [comment]
Hi!

Thanks for reporting and for opening the PR.

Yeah, I think the fix for this should be to just make the `suggested_tags` optional, maybe alongside all other undocumented fields? I'll think about it some more after looking at your PR.
