### ISSUE TITLE
Initial setup of OAuth as in README is broken

### ISSUE THREAD

**Issue by tomjonandy** [pawelad/pymonzo#9]
When using the python interpreter to set up OAuth as suggested in the README, it fails because:
 - `MonzoAPI._token` is set in `MonzoAPI.__init__` by calling `self_get_oauth_token()`
 - This calls `self._save_token_on_disk()` *before* returning
 - `_save _token_on_disk()` tries to do `token = self._token.copy()`, but fails with `AttributeError: 
'MonzoAPI' object has no attribute '_token'` becasue `_token` isn't set yet because `_get_oauth_token()` has not yet returned.

**Comment by pawelad** [comment]
You're absolutely right - thanks for the report and sorry for the bug. Should be fixed in just released [v0.10.3](https://github.com/pawelad/pymonzo/releases/tag/v0.10.3)

**Comment by tomjonandy** [comment]
Great, thanks for the speedy response!
